# Set scroll history to 100,000 lines
set-option -g history-limit 100000

# reload config file
bind r source-file ~/.tmux.conf \; display "Config Reloaded!"
#bind x confirm-before kill-session
bind X kill-session

set-option -g default-terminal "tmux-256color"

bind \\ split-window -h
bind b split-window -h
bind - split-window -v
bind v split-window -v

# Move between panes in one terminal
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Move between terminal windows
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+
bind o last-window

# Resize pane shortcuts
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# When renaming the window, remove the pre-filled old name in the prompt
# For syntax, check "command-prompt" in tmux manpage
unbind ,
bind , command-prompt -p "Rename window:" "rename-window %%"

# enable mouse support for switching panes/windows
setw -g mouse on

# set the escape time to zero (ok on local computer)
# https://github.com/tmux/tmux/wiki/FAQ#what-is-the-escape-time-option-is-zero-a-good-value
#set -sg escape-time 0

# use Alt+{h,l} to navigate between windows
bind -n M-h previous-window
bind -n M-l next-window

# vim
# set vi mode for copy mode
setw -g mode-keys vi
unbind P
bind P paste-buffer
bind -Tcopy-mode-vi 'v' send -X begin-selection
bind -Tcopy-mode-vi 'y' send -X copy-pipe-and-cancel "tmux save-buffer - | reattach-to-user-namespace pbcopy"
# for vim.autoread to work properly
set-option -g focus-events on
# don't jump to bottom after highlighting an area with the mouse
unbind -T copy-mode-vi MouseDragEnd1Pane

