auto-format = true

[[language]]
name = "markdown"
text-width = 80
rulers = [80]
soft-wrap = { enable = true}
# soft-wrap = { enable = true, wrap-at-text-width = true }

[[language]]
name = "c"
formatter = { command = "clang-format" }

# [language-server.tinymist]
# command = "tinymist"
# config = { preview.background.enabled = true, preview.background.args = ["--data-plane-host=127.0.0.1:1337", "--invert-colors=never", "--open"] }

[[language]]
name = "typst"
text-width = 80
# soft-wrap = { enable = true, wrap-at-text-width = true }
soft-wrap = { enable = true}
rulers = [80]

# [[language]]
# name = "todotxt"
# file-types = ["todo.txt"]
# scope = "todo.txt"
# formatter = { command = "cat" }


[[language]]
name = "mail"
file-types = [
  { glob = "/tmp/neomutt-*" }
]

