[font]
#size = 10 # monospace
size = 11.5

[font.normal]
style = "regular"
#family = "Monospace"
#family = "Noto Sans Mono"
family = "Iosevka Term"
#family = "Jetbrains Mono Nerd Font"
#family = "Hermit"
#family = "Cousine Nerd Font"
#family = "Fira Code"
#family = "Hack Nerd Font Mono"


[[hints.enabled]]
binding.key = "O"
binding.mods = "Control|Shift"
command = "xdg-open"
mouse.enabled = true
post_processing = true # remove trailing chars that are not likely part of URIs
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^<>\"\\{-}^⟨⟩` \n)\\]]+"
# orig:
#regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"
#regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)(.[^\\.\\n, ])*[A-z0-9]?"
# PCR2 expression that works with negative lookahead: https?:\/\/((?![.,]$).)*
# lookahead/behind is not supported in alacritty, afaict

[[hints.enabled]]
action = "Copy"
binding.key = "Y"
binding.mods = "Control|Shift"
mouse.enabled = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^<>\"\\{-}^⟨⟩` \n)\\]]+"

[[hints.enabled]]
action = "Copy"
binding.key = "H"
binding.mods = "Control|Shift"
# mouse.enabled = true
post_processing = false
regex = "[0-9a-f]{40}"

[mouse]
hide_when_typing = true
bindings = [
    { mouse = "Left", mods = "Shift", command = "xdg-open" },
]


[window]
decorations = "none"
dynamic_title = false
startup_mode = "Maximized"
#opacity = 0.90
# padding = { x = 3, y = 3 }

[general]
import = [
"~/.config/alacritty/alabaster_dark.toml",
]
