import = [
"~/.config/alacritty/alabaster_dark.toml",
]

[font]
size = 11
# size = 10.0

[font.normal]
#family = "Monospace"
family = "iosevka term"
style = "regular"
# family = "Hermit"
#family = "Cousine Nerd Font"
#family = "Fira Code"
# family = "Hack Nerd Font Mono"


[[hints.enabled]]
command = "xdg-open"
mouse.enabled = true
# orig:
#regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^<>\"\\{-}^⟨⟩` \n)\\]]+"

#regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)(.[^\\.\\n, ])*[A-z0-9]?"
# PCR2 expression that works with negative lookahead: https?:\/\/((?![.,]$).)*
# lookahead/behind is not supported in alacritty, afaict

[hints.enabled.binding]
key = "O"
mods = "Control|Shift"

[[hints.enabled]]
action = "Copy"
post_processing = false
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^<>\"\\{-}^⟨⟩` \n)\\]]+"

[hints.enabled.binding]
key = "Y"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true

[[hints.enabled]]
action = "Copy"
post_processing = false
regex = "[0-9a-f]{40}"

[hints.enabled.binding]
key = "H"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true

[mouse]
hide_when_typing = true
bindings = [
    { mouse = "Left", mods = "Shift", command = "xdg-open" },
]


[window]
decorations = "none"
dynamic_title = false
startup_mode = "Maximized"
#opacity = 0.95
#padding = { x = 20, y = 20 }


#[colors.primary]
#background = "#111111"
